### ISSUE TITLE
Update to support M1 architecture

### ISSUE THREAD

**Issue by kikiya** [lightbend/kalix-javascript-sdk#99]
Currently the install fails when using on M1 architecture Macs but the current fix is pretty straight forward:

Based on issue https://github.com/protocolbuffers/protobuf/pull/8557 

We should be able to add these lines and might want to reference the above PR in comments. 

```
case "arm64":
          return makeDownloadFile("osx-x86_64"); 
```

The change should be added in this block -- 

https://github.com/lightbend/akkaserverless-javascript-sdk/blob/69f5578a000b990d02d685ffcf8514e89d985e48/sdk/bin/download-protoc.js#L17

**Comment by johanandren** [comment]
One more step is some details about building the docker image using `docker buildx` with amd64 as platform.

**Comment by johanandren** [comment]
Adding that osx-x86_64 then goes on to fail with 
```
[ 66%] Building C object CMakeFiles/cpu_features.dir/src/cpuinfo_arm.c.o
In file included from /Users/johan/Code/Lightbend/akka-serverless/akkaserverless-javascript-sdk/sdk/node_modules/cpu-features/deps/cpu_features/src/cpuinfo_arm.c:15:
/Users/johan/Code/Lightbend/akka-serverless/akkaserverless-javascript-sdk/sdk/node_modules/cpu-features/deps/cpu_features/include/cpuinfo_arm.h:118:2: error: "Including cpuinfo_arm.h from a non-arm target."
#error "Including cpuinfo_arm.h from a non-arm target."
 ^
```

in "cpu_features" https://github.com/google/cpu_features/pull/150

So looks like moving forward with this is blocked by that

**Comment by johanandren** [comment]
Looks like this _may_ be fixed by the switch in what proto/grpc tooling we use in current main.

**Comment by johanandren** [comment]
Almost, it is not possible to build the kalix-tools because it depends on a native image of the codegen which is not available for Macos arm64.

**Comment by johanandren** [comment]
I got that to work locally by doing the following:
 * install a graalvm that works on m1 ("22.1.0.r17-grl" with sdkman)
 * point the `nativeImageGraalHome` in `kalix-codegen-js-cli` to the graal directory
 * sbt kalix-codegen-js-cli/nativeImage
 * copy the built binary somewhere
 * set/export env KALIX_NPMJS_CODEGEN_BINARY to the complete path of that somewhere

**Comment by pvlugter** [comment]
Looks like CircleCI doesn't yet support M1, so we won't be able to automate this yet.

https://circleci.canny.io/cloud-feature-requests/p/support-new-m1-arm-based-macs

Can it just run the x64 codegen binary via rosetta for now? (don't have an M1 mac to try it out)

Looks like there are protoc versions with osx-aarch downloads now.

Will `nativeImageVersion := "22.1.0"` work to have an M1 compatible graalvm downloaded automatically?

**Comment by pvlugter** [comment]
Longer term, could make more sense to convert the codegen over to TypeScript, and not have the native image binaries.

**Comment by pvlugter** [comment]
Published `1.0.0-M9` with changes from #358 — use protoc osx-aarch download, use x86 binary (with rosetta) for codegen.

**Comment by johanandren** [comment]
Looks like 1.0.0-M9 works nicely up to building a docker image.

Building the image needs a cross build using buildx (this is how I've solved that in the Scala SDK samples: https://github.com/lightbend/kalix-jvm-sdk/blob/main/samples/scala-doc-snippets/build.sbt#L18 ), or you end up with an arm64 image on docker hub which can't be deployed to Kalix.

**Comment by johanandren** [comment]
For the record, this is the command to cross-build and push the js-customer-registry sample: 

```
docker buildx build --platform=linux/amd64 -f Dockerfile -t johanandren/js-customer-registry:2022-06-21 ../../.. --push
```
